[general]
spawnCorruptedLunarians = true
spawnStarCrawlers = true
spawnMartianRaptors = true
spawnMoglers = true
spawnSulfurCreepers = true
doEntityGravity = true
doLivingEntityGravity = true
acidRainBurns = true
doOxygen = true
doSpaceMuffler = true
oxygenTankSize = 40500
hammerDurability = 64
giveAstroduxAtSpawn = false
oxygenBarXOffset = 0
oxygenBarYOffset = 0
energyBarXOffset = 0
energyBarYOffset = 0
spawnLunarianWanderingTrader = true
orbitGravity = 3.0
oxygenDamage = 1
freezeDamage = 1
heatDamage = 2
acidRainDamage = 3
allowFlagImages = true
disabledPlanets = []
[spaceSuit]
spaceSuitTankSize = 81000
netheriteSpaceSuitTankSize = 162000
netheriteSpaceSuitHasFireResistance = true
jetSuitSpeed = 0.8
jetSuitUpwardsSpeed = 0.5
jetSuitEnergyPerTick = 60
jetSuitTankSize = 324000
jetSuitMaxEnergy = 1000000
enableJetSuitFlight = true
jetSuitProtectionMultiplier = 1
jetSuitArmorToughness = 5
spawnJetSuitParticles = true
[vehicles]
fallingExplosionThreshold = -1.2
fallingExplosionMultiplier = 0.7
gravity = -2.0
moveCameraInVehicle = true
[rocket]
atmosphereLeave = 600
countDownTicks = 200
acceleration = 0.005
maxSpeed = 0.5
entitiesBurnUnderRocket = true
tankSize = 243000
fuelLaunchCost = 243000
efficientFuelLaunchCost = 81000
[rover]
explodeRoverInLava = true
fuelPerSecond = 810
turnSpeed = 3.0
maxTurnSpeed = 6.0
deceleration = 0.9
minSpeed = -0.2
maxSpeed = 0.3
tankSize = 243000
[lander]
boosterThreshold = -0.1
boosterSpeed = 0.1
[coalGenerator]
maxEnergy = 9000
energyPerTick = 10
[compressor]
maxEnergy = 9000
energyPerTick = 10
[fuelRefinery]
maxEnergy = 9000
energyPerTick = 30
tankSize = 243000
[oxygenLoader]
maxEnergy = 9000
energyPerTick = 10
tankSize = 243000
[oxygenDistributor]
maxEnergy = 20000
fluidConversionEnergyPerTick = 5
tankSize = 486000
maxBlockChecks = 2000
refreshTicks = 60
oxygenMultiplier = 0.8
energyMultiplier = 3.0
[solarPanel]
maxEnergy = 18000
energyMultiplier = 1.0
[waterPump]
maxEnergy = 9000
energyPerTick = 10
tankSize = 486000
transferPerTick = 810
deleteWaterBelowWaterPump = true
[energizer]
maxEnergy = 2000000
energyPerTick = 170
[cryoFreezer]
maxEnergy = 30000
energyPerTick = 24
tankSize = 243000
